import Head from 'next/head'
import Image from 'next/image'
import Event from '../components/Event';
import Link from 'next/Link'

import Hero from '../components/Hero'
import Post from '../components/Post';
import Sidebar from '../components/Sidebar';
import styles from '../styles/Home.module.scss'
export default function Home() {
  const Img1 = "../images/nnr1.jpg"
  return (
    <div className={styles.container}>
      <Head>
        <title>National Nuclear Regulator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero />
        <div className={styles.home_content}>
          <section className={styles.home_content_section} >
            <div className={styles.home_content_img}>
             <img 
             src={Img1}
             width="100%"
             />
            </div>

            <div className={styles.home_content_description}>
              <p>NNR staff create nuclear safety awareness amongst local communities in Kouga, Eastern Cape Province</p>
              <button className={styles.buttonPrimary}>
                <Link href="/">
                  <a href="">Read more</a>
                </Link>
              </button>
            </div>
            <h1>Introduction to the NNR</h1>
            <p>
            The National Nuclear Regulator (NNR) is a public entity which is established and governed in terms of Section 3 of the National Nuclear Regulator Act, (Act No 47 of 1999) to provide for the protection of persons, property and the environment against nuclear damage through the establishment of safety standards and regulatory practices.

            </p>
            <p>
            It is responsible for granting nuclear authorisations and exercising regulatory control related to safety over the siting, design, construction, operation, manufacture of component parts, and the decontamination, decommissioning and closure of nuclear installations; and vessels propelled by nuclear power or having radioactive material on board which is capable of causing nuclear damage.
            </p>
          </section>
         
          <Sidebar />
        </div>
      </div>
    </div>
  )
}

